### ISSUE TITLE
Switching to Gradle Composite Build for Dependencies

### ISSUE THREAD

**Issue by solvingj** [Azure/autorest-clientruntime-for-java#126]
I'm not sure if Azure team is aware of this feature, but it's particularly relevant to the Azure projects for Java, as there are so many inter-dependencies.  It might eliminate the need for the intermediate maven repository for hosting snapshots: 
https://blog.gradle.org/introducing-composite-builds

It's still in incubation status, but the AutoRest and client runtimes seem like good candidates to try it out on.

**Comment by jianghaolu** [comment]
Thanks for sharing this! It looks like you've shared some of the pains that we had :)
Currently, the way we handle it is to include both projects in Eclipse or Intellij. They both support referencing local dependencies.

What we really look for is a composite build across multiple repos. Almost like a dynamically generated maven feed. That would really simplify our CI and testing process.

**Comment by solvingJ** [comment]
You are not alone. It's not a simple thing to implement, but I believe the next evolution in the build systems is to support remote GIT references directly, just like normal maven/nuget/npm references. The key being that the cloning and compilation is transparent to the user.  Also, there would have to be some intelligence around snapshots, caching, etc.   However, this would be especially valuable for large teams like yours who are trying to rapidly evolve multiple libraries, which depend on each other, and which have huge communities that are developing products on top of those libraries.   Frankly, the CI workflow is not quite designed to handle your particular use case.  It's too much changing too fast with too many relationships. 

At least within Java, it's possible (even likely) that a Gradle plugin COULD be created to for this use case.  With Gradle's extensibility, it might not even be that hard of a plugin to write.  If you add up all the time your team spends orchestrating the snapshot maven repos, CI systems, and troubleshooting version conflicts, it would more than justify the cost of developing a plugin to streamline all that. 

Just my thoughts :)

**Comment by RikkiGibson** [comment]
This could be quite useful but a move to Gradle is unlikely in the near future for us.

Re: the git references thing, it looks like someone has created such a solution: https://jitpack.io
