### ISSUE TITLE
Trailing slash (/) in the resource URI

### ISSUE THREAD

**Issue by praneetloke** [Azure/autorest-clientruntime-for-java#180]
I am using this library with the [azure-keyvault-java](https://github.com/Azure/azure-keyvault-java) library. I was getting `401 Unauthorized` no matter what I did when trying to get secrets from a KeyVault. When I looked into it, it was the `AzureTokenCredentials.getToken` method at this [line](https://github.com/Azure/autorest-clientruntime-for-java/blob/master/azure-client-runtime/src/main/java/com/microsoft/azure/credentials/AzureTokenCredentials.java#L50). The only way I could override this was to extend `ApplicationTokenCredentials`, which extends this class and overrode the `getToken` method there. I think this is a roundabout way to get around the problem in my opinion.

My questions are:
- Is there a reason for marking this method as `final` in `AzureTokenCredentials`?
- I am not sure if the trailing slash is a problem for any other resources, could you just remove the trailing slash from this [line](https://github.com/Azure/autorest-clientruntime-for-java/blob/master/azure-client-runtime/src/main/java/com/microsoft/azure/credentials/AzureTokenCredentials.java#L50)?

**Comment by jianghaolu** [comment]
@praneetloke You might find this class helpful: https://github.com/Azure/azure-keyvault-java/blob/master/azure-keyvault/src/main/java/com/microsoft/azure/keyvault/authentication/KeyVaultCredentials.java

**Comment by praneetloke** [comment]
@jianghaolu thanks for the tip! I will try this out soon and report back.

**Comment by RikkiGibson** [comment]
Please reopen if you still need help with this @praneetloke.
