### ISSUE TITLE
RestProxy and expected response codes

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/autorest-clientruntime-for-java#202]
Swagger specifies what response codes are valid for a method and what they mean. 

e.g. https://github.com/Azure/azure-rest-api-specs/blob/current/specification/compute/resource-manager/Microsoft.Compute/2017-03-30/compute.json#L494

```
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/OperationStatusResponse"
            }
          },
          "202": {
            "description": "Accepted"
          },
          "204": {
            "description": "No Content"
          }
        }
```

The different response codes can have different return types associated with them. I'm guessing that there's usually one return type or nothing--some kind of in-progress value is given back through a header or something. Right now, we have generated code in azure-sdk-for-java for each service method that validates those response codes and otherwise wraps up the response body in an exception.

Perhaps there should be an annotation on a service method which indicates what response codes are acceptable? It would look something like this:

```
interface UsagesService {
    @Responses({ 200, 202, 204 })
    @Headers({ "Content-Type: application/json; charset=utf-8" })
    @GET("subscriptions/{subscriptionId}/providers/Microsoft.Storage/usages")
    Observable<PageImpl<UsageInner>> list(
        @PathParam("subscriptionId") String subscriptionId,
        @QueryParam("api-version") String apiVersion,
        @HeaderParam("accept-language") String acceptLanguage,
        @HeaderParam("User-Agent") String userAgent);
}
```

Does this handle our use case?

**Comment by RikkiGibson** [comment]
Leaning toward thinking it's probably not necessary to have annotations for this, as the expected response codes across Azure management are pretty consistent (either 200, or 200/202/204 where only 200 returns an entity)

**Comment by anuchandy** [comment]
We need to register the models for errors as there can be multiple model for different error codes and these error models may not be same across different swaggers.

**Comment by RikkiGibson** [comment]
I suggest having a default behavior of CloudException for any non-2xx response code, and then something like an annotation on each method for each type of custom exception that can be thrown. @daschult this is probably the main thing that RestProxy can start doing which will make `ResponseBuilder` and `ServiceResponse` in the runtime which depend on Retrofit stuff unnecessary.

```
interface MyService {
    @ErrorResponse(405, CustomErrorType.class)
    @ErrorResponse(400, OtherErrorType.class)
    Entity myMethod(...)
}

**Comment by RikkiGibson** [comment]
Clarification: [Azure OpenAPI guidelines](https://github.com/Azure/azure-rest-api-specs/blob/current/documentation/openapi-authoring-manual-guidelines.md) explain that error responses are included in the "default" case of the "responses" object in the specification. Any specified response status code is an "accepted" response status, which may have some data type defined as its body. We have a mechanism in AutoRest which looks for the nearest common ancestor of all the body data types for the "accepted" response statuses of an API method.

Long and short of it, it looks like the annotations we'll actually want look something like:

```java
interface MyService {
    @AcceptedResponses(200, 201, 400)
    @ErrorResponse(CatchallErrorType.class)
    Entity myMethod(...)
}
```

**Comment by daschult** [comment]
I was thinking about this, and I think rather than @AcceptedResponses we should use @ExpectedResponses. Accepted sounds to successful to me and it also reminds me of 202 ACCEPTED, where Expected sounds like its just something that we knew might happen from this particular API. I think @ErrorResponse is still fine though.
