### ISSUE TITLE
[RestProxy] Long running operations

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/autorest-clientruntime-for-java#209]
We need to support long running operations in the new runtime. There is a need for both e.g. a `create` method that polls the LRO and a `beginCreate` method that does not poll the LRO. This may be represented by an additional method in the service interface, where one has a `@PollLongRunningOperation` annotation and the other does not.

To achieve the correct behavior, it may be necessary to change RestProxy to an instance class and subclass it e.g. AzureRestProxy to call out to specific AzureClient methods for polling the LRO.

**Comment by RikkiGibson** [comment]
I'm slightly concerned about the potential for combinations to grow-- `create`, `createAsync`, `beginCreate`, `beginCreateAsync` for each LRO

**Comment by RikkiGibson** [comment]
(Wrote this up, but forgot to submit it yesterday..)
It's looking like there are two main cases RestProxy will handle:

1. Do the LRO and don't bug me until it's done or it's failed. This is represented by: 
```Single<VirtualMachine> create()```

2. Do the LRO, tell me when it's started, and tell me any content in the polling responses. This is represented by:
```Observable<OperationStatus<VirtualMachine>> beginCreate()```

OperationStatus will have sufficient information on it such that it can be serialized and polling can be resumed on a different host.
@daschult Feel free to hop in and tweak this if it isn't quite right.

**Comment by daschult** [comment]
No, that's correct. I'm wondering if we should change the name of "beginCreate()" to "createWithUpdates()"? I'm not sold on "createWithUpdates()" because it reminds me of "update()" commands. The issue I have with "beginCreate()" is that traditionally that sort of operation would return a token that you would use when you call an "endCreate()" function. In our case, however, we're not really returning anything. We're saying we'll notify you when there are polling updates, which we represent as "OperationStatus<VirtualMachine>". I feel like there's a better name than "beginCreate()" or "createWithUpdates()". Maybe "createWithStatusUpdates()"? "createWithPolling()"?

**Comment by RikkiGibson** [comment]
OK, to support this work, I should remove basically all the procedural gencode for LROs and generate interface method overloads with the appropriate return types.

**Comment by daschult** [comment]
Yes, that sounds right.

**Comment by RikkiGibson** [comment]
https://github.com/Azure/autorest-clientruntime-for-java/pull/220

**Comment by RikkiGibson** [comment]
Also, I'm moving forward with the assumption that we aren't interested in synchronous or callback-based overloads of "beginCreate". Monitoring all the polling events is a somewhat niche/advanced case and it seems reasonable to expect folks who want to do that to learn a little bit of Rx.

**Comment by daschult** [comment]
Correct. Let's assume that anyone who wants this advanced case (beginCreate) is going to use the asynchronous methods.

**Comment by RikkiGibson** [comment]
@daschult @anuchandy  There's a subtle issue going on in LROs with AzureProxy.

A method in a swagger spec will denote its expected response as 201. It looks like this is a true statement about the first HTTP call that initiates the long-running operation. Those expected response codes aren't intended to be used for the subsequent polling requests, which may eventually return 200 to indicate that the operation succeeded.

The trouble is that the same `SwaggerMethodParser` is being passed to `RestProxy.handleAsyncHttpResponse` in [AzureProxy.java#L157](https://github.com/RikkiGibson/autorest-clientruntime-for-java/blob/cfe30308301ea1229db77f1b14841f240c0c377c/azure-client-runtime/src/main/java/com/microsoft/azure/AzureProxy.java#L157), which is then unhappy about having received an unexpected response code of 200 when the operation completes successfully.

We used to get around this by just hard coding the response codes that we think are good in AzureClient.

This could be solved in the code generator by forcing any long running operations to have at least 200, 201 and 202 as ExpectedResponses, but it might be more appropriate to solve in AzureProxy somehow.

**Comment by RikkiGibson** [comment]
This is especially interesting for our `Single<Entity>` variants which emit just one event.

**Comment by RikkiGibson** [comment]
Also, it looks like the spec is that if a long running operation ends with provisioning state Failed, an error should be emitted.

**Comment by RikkiGibson** [comment]
@daschult is this work basically done?

**Comment by daschult** [comment]
We have a working implementation, but the autorest.java test cases don't all pass. So no, I'd say the work isn't quite done.

**Comment by daschult** [comment]
All of the tests in autorest.java pass, so I'm closing this.
