### ISSUE TITLE
Update to RxJava 2

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/autorest-clientruntime-for-java#228]
It looks like v2 of Azure SDK for Java will be a good opportunity to update to RxJava 2. There are bound to be a lot of little tweaks needed in the runtime, generator and management SDK to be compatible. Someone should probably take this on as a dedicated task to make it happen from end to end.

**Comment by RikkiGibson** [comment]
Usage of Single<T> is causing unpleasant rippling effects when I try to regenerate code for management SDK using the runtime-v2 branch of autorest.java and so on. This will probably take care of that issue at the same time.

**Comment by RikkiGibson** [comment]
RxNetty is incompatible with RxJava 2, so it'll be necessary to migrate to @jianghaolu's NettyRxAdapter as part of this task.

**Comment by RikkiGibson** [comment]
@jianghaolu how does this rate as a priority?

**Comment by jianghaolu** [comment]
@anuchandy would RxJava 2 help with the graph rework?

**Comment by RikkiGibson** [comment]
Done in #297
