### ISSUE TITLE
Parameterized Host Swagger Extension

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/autorest-clientruntime-for-java#234]
Right now we have the `@HostParam` attribute in the runtime. I'm working on fixing the autorest.java tests and the runtime so that HostParam is used correctly.

Consider the following test Swagger which has multiple host parameters.
https://github.com/Azure/autorest.testserver/blob/master/swagger/custom-baseUrl.json#L12

Right now we generate just one synthetic ParameterJv and use string concatenation followed by parsing to provide the values for all these parameters. This gen code is designed to handle the x-ms-parameterized-host in the Swagger linked above:
```
public Single<Void> getEmptyAsync(String accountName) {
    if (accountName == null) {
        throw new IllegalArgumentException("Parameter accountName is required and cannot be null.");
    }
    if (this.client.host() == null) {
        throw new IllegalArgumentException("Parameter this.client.host() is required and cannot be null.");
    }
    String parameterizedHost = Joiner.on(", ").join("{accountName}", accountName, "{host}", this.client.host());
    return service.getEmpty(parameterizedHost);
}
```

I haven't drilled down to the bottom of it, but I think RestProxy might not be dealing with these compound host parameters correctly, and this might be an opportunity to fix the specification and code generator to do this without convoluted string manipulation in Java.

**Comment by daschult** [comment]
Let's work together on coming up with a few good test cases to put into autorest-clientruntime-for-java when you get in today to try and figure this issue out.

**Comment by RikkiGibson** [comment]
This is really just a code generator issue. Multiple host parameters work fine in RestProxy.

**Comment by RikkiGibson** [comment]
Added coverage in #236. Fixed code generator in https://github.com/Azure/autorest.java/commit/eda7027
