### ISSUE TITLE
[MoonCake] Sign in fail in 1.1.0

### ISSUE THREAD

**Issue by adashen** [Azure/autorest-clientruntime-for-java#263]
Following error shows, when sign in azure mooncake with service principal file. 
{"error_description":"AADSTS50001: The application named https:\/\/management.core.windows.net\/ was not found in the tenant named 954ddad8-66d7-47a8-8f9f-1316152d9587.  This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant.  You might have sent your authentication request to the wrong tenant.\r\nTrace ID: 03a0e526-877c-48ed-8723-053777be0a00\r\nCorrelation ID: 9dd42f78-7fac-44cf-b80c-84d933df4345\r\nTimestamp: 2017-10-13 02:21:29Z","error":"invalid_resource"}
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.microsoft.azure.credentials.ApplicationTokenCredentials.acquireAccessToken(ApplicationTokenCredentials.java:145)

After investigation the issue, the root cause is, in https://github.com/Azure/autorest-clientruntime-for-java/blob/v1.1.0/azure-client-runtime/src/main/java/com/microsoft/azure/credentials/AzureTokenCredentials.java#L45 it uses environment.activeDirectoryResourceId() as the request resource. However, when loading service principal in https://github.com/Azure/autorest-clientruntime-for-java/blob/v1.1.0/azure-client-runtime/src/main/java/com/microsoft/azure/credentials/AzureTokenCredentials.java#L45 it only override the active directory url instead of the activeDirectoryResourceId.

The issue impacts all the mooncake user currently. Please help to fix it as soon as possible

**Comment by Eskibear** [comment]
currently we can workaround this issue by reverting to `v1.0.4`. But it would bring back the CloudException issue ( https://github.com/Azure/azure-sdk-for-java/issues/1858 ) which was fixed in `v1.1.0`.

**Comment by adashen** [comment]
1.1.1 could login but has problem in storage account. https://github.com/Microsoft/azure-tools-for-java/issues/1150

**Comment by RikkiGibson** [comment]
Please reopen if this is still a problem @adashen.
