### ISSUE TITLE
Outdated OkHttp dependency brings a security risk

### ISSUE THREAD

**Issue by wbachnik** [Azure/autorest-clientruntime-for-java#299]
Hi,

According to VulnDB scan, OkHttp 3.3.1 library contains a severe security risk: 

> OkHttp Non-ASCII ETag Header Handling Remote DoS
> 
> OkHttp contains a flaw that is triggered during the handling of non-ASCII ETag headers. This may allow a remote attacker to crash a process linked against the library.

Version 3.4.0 is reported not to contain this vulnerability, also the latest version is considered safe.
Please consider updating the OkHttp library dependency, as the vulnerability affects clients using `autorest-clientruntime-for-java`. 

Thank you.

**Comment by jianghaolu** [comment]
Good catch! Reading their change logs...

**Comment by wbachnik** [comment]
Thanks for the quick resolution!

Just one more question, I see the version still declared in `pom.xml` is `1.1.2-SNAPSHOT`, while version `1.2.0` that has updated dependency on OkHttp seems to be publicly available, e.g.: https://mvnrepository.com/artifact/com.microsoft.azure/autorest-clientruntime-for-java/1.2.0. I also don't see a matching release on the releases page. Where did it come from? Can I safely declare dependency on `1.2.0` in my project now? Thanks!
