### ISSUE TITLE
Empty XML elements should be represented by empty strings/collections

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/autorest-clientruntime-for-java#381]
A payload like this:
```xml
<Root>
    <Child>
        <Item>1</Item>
        <Item>2</Item>
        <Item>3</Item>
    </Child>
</Root>
```
causes the Root.Child property to be a List instance with 3 items.

```xml
<Root>
    <Child />
</Root>
```
causes the Root.Child property to be null.

Similarly, a missing String property/attribute is represented as null. Objects containing unnecessarily null collections are a pain in the butt to use. We should see if we can make them empty by default instead.

**Comment by RikkiGibson** [comment]
Note https://github.com/FasterXML/jackson-dataformat-xml/issues/124
There might be some reasonably elegant workaround-- worse case we can change model generation again to accommodate.

**Comment by rickle-msft** [comment]
Consider support for the case where the child list is not actually included as an element, so 
`</Root>` would still put an non-null empty list in Root.Child even though no child element is even included.
