### ISSUE TITLE
SharedChannelPool synchronization on interned object

### ISSUE THREAD

**Issue by davidmoten** [Azure/autorest-clientruntime-for-java#388]
@RikkiGibson just started looking at the code and noticed straight away that you are using 
```java
private final Object sync = -1;
```
for synchronization. Given that some integers are interned (and possible future interning changes could affect you) this could get you in to trouble. I'd suggest just doing:

```java
private final Object sync = new Object();
```

**Comment by RikkiGibson** [comment]
Thank you--good idea.

**Comment by RikkiGibson** [comment]
@jianghaolu was there any specific reason to use -1 for the lock?

**Comment by RikkiGibson** [comment]
Fixed.
