### ISSUE TITLE
v2: SharedChannelPool wait() not in loop

### ISSUE THREAD

**Issue by davidmoten** [Azure/autorest-clientruntime-for-java#390]
The call to `wait()` below should be in a loop (that checks a condition):
```java
if (leased.size() >= poolSize && !closed) {
    synchronized (sync) {
        sync.wait();
    }
}
```
From the javadoc of `wait()`:

>interrupts and spurious wakeups are possible, and this method should always be used in a loop

I imagine this code should be 

```java
synchronized(sync) {
    while (leased.size() >= poolSize && !closed) {
        sync.wait();
    }
}
```

**Comment by RikkiGibson** [comment]
Fixed.
