### ISSUE TITLE
Usage of retrofit and OkHttp cause excessive thread pool creation

### ISSUE THREAD

**Issue by menih** [Azure/autorest-clientruntime-for-java#424]
Integrating with Azure cause large number of OkHttp threads to be created. We're looking for ways to control this as we want to keep thread count under control. Is there a way to do it?

**Comment by RikkiGibson** [comment]
How many threads do you see getting created? You may wish to experiment with [OkHttpClient.Builder.dispatcher(Dispatcher)](https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.Builder.html#dispatcher-okhttp3.Dispatcher-) and [Dispatcher.setMaxRequests](https://square.github.io/okhttp/3.x/okhttp/okhttp3/Dispatcher.html#setMaxRequests-int-).

Please follow up if you learn anything new :)

**Comment by menih** [comment]
See, the thing is, OkHttp is packaged with Azure SDK and not consumed
directly by my application. It is a black box for me, how can I we change
the settings Azure SDK usage of OkHttp?

**Comment by RikkiGibson** [comment]
You should be able to set the OkHttpClient.Builder on a RestClient, then provide that to *Manager.authenticate() or the constructor on the generated client.

**Comment by jianghaolu** [comment]
In the latest SDK release you can do that through 

```java
Azure.configure()
    .useHttpClientThreadPool(true)
    .withDispatcher(new Dispatcher(myThreadPool))
    ....
```

to control the thread pool. This test https://github.com/Azure/autorest-clientruntime-for-java/blob/master/client-runtime/src/test/java/com/microsoft/rest/ConnectionPoolTests.java#L34 shows the usage and effect. (on `RestClient`, but same thing with `Azure`)
