### ISSUE TITLE
Managed Identity/IMDS auth: Configurable retry time-out

### ISSUE THREAD

**Issue by arluca** [Azure/autorest-clientruntime-for-java#440]
Currently, the retry logic in the Azure SDKs for Managed Identity token generation can make the current thread wait for as long as 15 minutes. For response time sensitive services this might not be acceptable. It could also result in service unavailability if all threads are blocked for a token to be generated when a sudden burst arrives after a cold start.
The developer may want to fast fail after certain time interval says for example 10 seconds if the call is still failing.
Can we make the retry max configurable?

**Comment by RikkiGibson** [comment]
@jianghaolu any idea what the status is on the auth functionality getting spun out into its own package, so we can get this request to the right people?

**Comment by arluca** [comment]
Any update on this one? Is there a way I can limit the retry today?

**Comment by jianghaolu** [comment]
https://github.com/jianghaolu/autorest-clientruntime-for-java/commit/4e2b89f184af343c41da83706ae011fb6dd7926f in PR #463 addresses this. Please review. Thanks!

**Comment by RikkiGibson** [comment]
This is setting the max number of retries, right? People can't set how long to wait before retrying with this change--they still have to use the Fibonacci exponential backoff thing we're apparently doing in there. Why does this thing, for example, potentially wait for 6765 seconds before doing the final retry by default? Are we seriously operating on that kind of a timeframe for obtaining MSI credentials in some cases?

**Comment by arluca** [comment]
The ask from the customer is to give an option for them to specify, the max retry. For example, "Only retry for 10 seconds total, and then timeout. 

The original reason we added the retries, was to enable the scenarios where the Managed identities subsystem was being updated, or the customer had hit the throttle limits. My understanding is that we would only ever see delays (worst case) in the magnitude of ~10 min. 

Adding @yugangw-msft for awareness.

**Comment by jianghaolu** [comment]
@RikkiGibson I'm not aware why Fibonacci - based on the principle "if I don't understand the code I'm not going to touch it" I didn't touch it. 

The technical reason for waiting for extended time is the MSI tokens are acquired from a few Windows hosts. They need to get updated on a monthly basis which can take a few minutes.

**Comment by RikkiGibson** [comment]
Fair enough :)

**Comment by jianghaolu** [comment]
I'll first add this in 1.6.1 and when @anuchandy comes back from his leave we can always change the retry timeout numbers.

**Comment by arluca** [comment]
Great! Thank you all. If you have an ETA for when 1.6.1 should be available, please let me know, as this item has been lingering for a while now. :)

**Comment by jianghaolu** [comment]
I'm doing the release now should be available later today.

**Comment by arluca** [comment]
Fantastic!
