### ISSUE TITLE
2.0.0-beta2 unusable due to packaging errors

### ISSUE THREAD

**Issue by rocketraman** [Azure/autorest-clientruntime-for-java#443]
I am attempting to use the Azure Storage SDK for Java v10, but am unable to because it depends on `com.microsoft.rest.v2:client-runtime:2.0.0-beta2`. As reported in https://github.com/Azure/azure-storage-java/issues/326, I am unable to resolve this package, because it references a SNAPSHOT version of the parent POM.

Gradle reports:

```
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve com.microsoft.rest.v2:client-runtime:2.0.0-beta2.
     Required by:
         project : > com.microsoft.azure:azure-storage-blob:10.0.0-Preview
      > Could not resolve com.microsoft.rest.v2:client-runtime:2.0.0-beta2.
         > inconsistent module metadata found. Descriptor: com.microsoft.rest.v2:client-runtime:2.0.0-SNAPSHOT Errors: bad version: expected='2.0.0-beta2' found='2.0.0-SNAPSHOT'
```

**Comment by RikkiGibson** [comment]
[client-runtime-2.0.0-beta3](https://repo.maven.apache.org/maven2/com/microsoft/rest/v2/client-runtime/2.0.0-beta3/) is out and appears to solve the malformed POM issue.

Thanks again for letting us know, and my apologies that you had to pull down our sources and install manually to get things working.

**Comment by rocketraman** [comment]
Thanks for the quick response!
