### ISSUE TITLE
Add new data plane token audience

### ISSUE THREAD

**Issue by alexeldeib** [Azure/autorest-clientruntime-for-java#461]
Related to https://github.com/Azure/azure-sdk-for-java/pull/2113, I'd like two add two new AAD resource URIs for authentication with Log Analytics and Application Insights APIs to query metrics/events/logs. The resources are:

https://api.loganalytics.io
https://api.applicationinsights.io

I may try to make a PR for this, but i'm not sure got all the right spots 😊 
Thanks!

**Comment by jianghaolu** [comment]
PR is open for this please review https://github.com/Azure/autorest-clientruntime-for-java/pull/463
