### ISSUE TITLE
Examples of Async for Kubernetes Clusters

### ISSUE THREAD

**Issue by shashank-g172** [Azure/autorest-clientruntime-for-java#480]
Hello,

I'm reading through the wall of documentation that is guava and how the ServiceFuture is built on top of it. I'm wondering if anybody could give me a sort of quick example on how I could asynchronously create the Kubernetes cluster using the SDK. So far, I was able to get this:

ServiceFuture clusterFuture = azure.kubernetesClusters().define(aksName)
.withRegion(region).withNewResourceGroup(resourceGroup).withLatestVersion()
.withRootUsername(rootUserName).withSshKey(keys.getSshPublicKey())
.withServicePrincipalClientId(clientId).withServicePrincipalSecret(key)
.defineAgentPool("agentpool").withVirtualMachineCount(1)
.withVirtualMachineSize(ContainerServiceVMSizeTypes.STANDARD_D2_V2).attach()
.withDnsPrefix("dns-" + aksName).createAsync(callback);

where callback is defined as:

      ServiceCallback<KubernetesCluster> callback = new ServiceCallback<KubernetesCluster>() {
        @Override
        public void failure(Throwable t) {
          logger.info("Kubernetes cluster not created yet.Please wait...");
        }

        @Override
        public void success(KubernetesCluster result) {
          String fqdn = result.fqdn();
          if (result.provisioningState().equals("Succeeded")) {
            logger.info("Cluster successfully created and running at: {}", fqdn);
          }
        }
      };

But it might help if anybody could point me to a working example to monitor the state of the cluster. The only flag I'm measuring success or failure for now is the provisioningState on the KubernetesCluster object.

I found this example for an Async virtual machine creation operation: https://github.com/Azure-Samples/compute-java-manage-vm-async/blob/master/src/main/java/com/microsoft/azure/management/compute/samples/ManageVirtualMachineAsync.java

but the "right" way of doing this would really help. 

Thanks!

**Comment by RikkiGibson** [comment]
@anuchandy any suggestion on where shashank should look?

**Comment by shashank-g172** [comment]
Actually I was able to figure out how the service Callback worked, and I was able to create the cluster asynchronously. 

If anybody's interested, I just created a static inner class for the ServiceFuture class and set up a boolean variable to flip to true on success and polled on that variable. 

Thanks @RikkiGibson
