### ISSUE TITLE
AzureJacksonAdapter failing to parse XML error responses

### ISSUE THREAD

**Issue by ardias** [Azure/autorest-clientruntime-for-java#483]
Hi all,
not sure if is this should be an issue with the library, but when using the Sdk java libs to list ServiceBus Topic subscriptions I'm getting a 404 and the body is XML  instead of Json which throws a JsonParseException instead of the proper "Not found" error (trying to convert to CloudError instance).
Example:

`java.lang.RuntimeException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('﻿' (code 65279 / 0xfeff)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: ﻿<?xml version="1.0" encoding="utf-8"?><entry xmlns="http://www.w3.org/2005/Atom"><id>uuid:20b77e97-bcbb-4ca0-925b-9637387de32f;id=14714</id><title type="text"></title><updated>2018-08-29T14:34:20Z</updated><content type="application/xml"><Error xmlns=""><Message>No HTTP resource was found that matches the request URI '$uri removed for privacy$/subscriptions?api-version=2015-08-01'.</Message></Error></content></entry>; line: 1, column: 2]`

**Comment by RikkiGibson** [comment]
The success response must be encoded in JSON for the currently published azure-mgmt-servicebus library to be able to deserialize it.. does that mean only the errors are given in XML? Is that allowed in ARM @jianghaolu?

**Comment by ardias** [comment]
. Haven't checked other types of errors because it's the only one I'm getting. And only in ServiceBus from what I can see.

**Comment by jianghaolu** [comment]
It's a service error to return XML in ARM. If you have an HTTP log we can forward to the service team.

**Comment by ardias** [comment]
Thanks for looking into it. Let me see if I can get that log for you.
