### ISSUE TITLE
Don't log HTTP failure when LogLevel is NONE

### ISSUE THREAD

**Issue by jianghaolu** [Azure/autorest-clientruntime-for-java#512]
Today in our code https://github.com/Azure/autorest-clientruntime-for-java/blob/master/client-runtime/src/main/java/com/microsoft/rest/interceptors/LoggingInterceptor.java#L118

We log a failure regardless of the log level.

**Comment by lmazuel** [comment]
@jianghaolu for what I see, we log and throw, so the caller as the opportunity to re-log the message if he wants to right?
Meaning we should probably keep that log at a low log level (thoughts?)

**Comment by jianghaolu** [comment]
Fixed via https://github.com/Azure/autorest-clientruntime-for-java/pull/514
