### ISSUE TITLE
 [v3] HttpClient as an interface rather than an abstract class

### ISSUE THREAD

**Issue by anuchandy** [Azure/autorest-clientruntime-for-java#550]
#### [Details from @JonathanGiles]:

1. Have you considered making HttpClient an interface rather than an abstract class?
2. Is HttpClientFactory used at all anymore?

**Comment by anuchandy** [comment]
1. We thought of it, but holding on doing it until we address https://github.com/Azure/autorest-clientruntime-for-java/issues/553
2. HttpClientFactory not used, just removed it in the [PR](https://github.com/Azure/autorest-clientruntime-for-java/pull/560), [commit](
https://github.com/Azure/autorest-clientruntime-for-java/pull/560/commits/0f80715e93284e86deae1267666a8950641ae4e7).

**Comment by anuchandy** [comment]
We have a method `createDefault()` in HttpClient abstract class to create default client, so that user can do

```java
HttpClient client = HttpClient.createDefault();
```

We cannot call default method in an interface like above, it requires an instance.

e.g following code won't compile.

```java
    interface Foo {
        default Foo createDefault() {return null; }
    }
//
Foo foo = Foo.createDefault();
```

**Comment by JonathanGiles** [comment]
You can create static or default methods in interfaces in Java 8. What specific problem are you encountering?

**Comment by anuchandy** [comment]
@JonathanGiles my bad, yes we can use static for creating default client. This is done in the PR https://github.com/Azure/autorest-clientruntime-for-java/pull/576

**Comment by JonathanGiles** [comment]
Great. Mark this issue as resolved!

**Comment by anuchandy** [comment]
Closing
