### ISSUE TITLE
[v3] Why does RestResponse not use the HttpHeaders type rather than the generic THeaders type

### ISSUE THREAD

**Issue by anuchandy** [Azure/autorest-clientruntime-for-java#551]
Discuss the use case of strongly typed Http headers with @JonathanGiles.

**Comment by anuchandy** [comment]
@JonathanGiles This is because some services has the concept of header entity, which holds values of subset of matching raw headers. 

Matching headers are the those with name matches with header entity property names and/or those with HeaderCollection annotation applied.

Storage data-plane SDK heavily uses this since they communicate lot of meaningful data through headers.

**Comment by anuchandy** [comment]
@JonathanGiles this is resolved as part of addressing this comment https://github.com/Azure/autorest-clientruntime-for-java/issues/554#issuecomment-470319112 in this PR https://github.com/Azure/autorest-clientruntime-for-java/pull/570

**Comment by JonathanGiles** [comment]
Please let me know when I should clone the repo and review API again

**Comment by JonathanGiles** [comment]
Let's close this issue then?

**Comment by JonathanGiles** [comment]
Can I flip this around just to make sure I'm understanding - why does HttpResponse and HttpRequest use HttpHeaders rather than Map<String, String> as the API? Is it just to make the case of having multiple values for a single key easier, or is there another reason?

**Comment by JonathanGiles** [comment]
I've consolidated RestResponse to use HttpHeaders, so now I think I'm happy everywhere.

**Comment by anuchandy** [comment]
Closing this then.
