### ISSUE TITLE
[v3] Can HttpMethod type be an enum

### ISSUE THREAD

**Issue by anuchandy** [Azure/autorest-clientruntime-for-java#552]
#### [Details from @JonathanGiles]:

1. Why is HttpMethod not an enum? (I quickly rewrote it as such and expected compilation errors, but they never occurred). 
2. This also means that ExpandableStringEnum could also be removed.

**Comment by anuchandy** [comment]
@JonathanGiles sure it can be enum but it's being ExpandableStringEnum allow us to accommodate new values. Fine with enum or ex-enum.

`ExpandableStringEnum` is an important type  to support expandable enum types in swagger spec. There are data plane and mgmt plane swaggers with lot of expandable enums. Having it in runtime is useful in general.

**Comment by JonathanGiles** [comment]
I'm fine with ExpandableStringEnum (assuming it's purpose is clearly documented), but by default we should try to avoid using it unless it makes sense? In the case of HttpMethod, this should be a plain enum?

**Comment by anuchandy** [comment]
Agree, let's make HttpMethod native enum

**Comment by anuchandy** [comment]
Closing this.
