### ISSUE TITLE
[v3] Can HttpClientConfiguration folded into HttpClient 

### ISSUE THREAD

**Issue by anuchandy** [Azure/autorest-clientruntime-for-java#553]
#### [Details from @JonathanGiles]:

I wonder if HttpClientConfiguration is needed, or if it can be folded into HttpClient or elsewhere? It seems odd to have extra API for setting just one configuration setting (proxy).

**Comment by anuchandy** [comment]
@jonathanGiles

 
We discussed this and were able to come up with a pattern for this. 
 
Example:
 
```java
HttpClient httpClient1 = HttpClient.createDefault();
 ```

This creates http client with default/no configuration applied.
 
Now we can apply a configuration as below, for example enable wiretap:
 
```java
HttpClient httpClient2 = httpClient1.wiretap(true);
 ```

Applying configuration will not mutate the original object httpClient1, it will continue to have default/no configuration. The httpClient2 object has all configuration from httpClient1 + wiretap enabled.
 
Now applying another (proxy) configuration,
 
```java
HttpClient httpClient3 = httpClient2.proxy(() -> new ProxyOptions(Type.HTTP, new InetSocketAddress("127.0.0.1", 8888));
 ```

Same behavior, httpClient2 won’t get mutated and will continue to have default config + wiretap.
httpClient3 has all configuration from httpClient2 + proxy.
 
Side note: for proxy we take a supplier, this another pattern we can validate which allows client to delay the proxy value computation.

**Comment by JonathanGiles** [comment]
Is there a reason for wanting to have HttpClient instances be immutable? If there is a reason, and it is justified, I think this will be ok. However, by default I worry this will feel counter-intuitive - that you are not actually modifying the instance, but instead creating a brand new instance on each call. E.g. the following code would create three instances of HttpClient, but only keep the third.

```java
HttpClient httpClient = HttpClient.createDefault().wiretap(true).proxy(() -> { ... });
```

**Comment by JonathanGiles** [comment]
I see now that this is also what Netty does. I have proposed a tweaked API [here](https://gist.github.com/JonathanGiles/7d1fc4a6a9078964c74f79a076147ad8)

**Comment by anuchandy** [comment]
Yes, reactor-netty client follows this pattern. I liked their approach. We could follow this pattern in general wherever configuration use-case exists.

Liked your gist, where we are getting rid of private classes for each configuration. I've updated client based on it in this - PR https://github.com/Azure/autorest-clientruntime-for-java/pull/576

**Comment by anuchandy** [comment]
Closing
