### ISSUE TITLE
[v3] Use Duration type instead of tuple of <long delayTime, ChronoUnit timeUnit>

### ISSUE THREAD

**Issue by anuchandy** [Azure/autorest-clientruntime-for-java#556]
#### [Details from @JonathanGiles]:

In RetryPolicy, consider using the Duration type, rather than (long delayTime, ChronoUnit timeUnit).

**Comment by anuchandy** [comment]
Implemented in this [PR](https://github.com/Azure/autorest-clientruntime-for-java/pull/560), [commit](
https://github.com/Azure/autorest-clientruntime-for-java/pull/560/commits/7ba1229a73c484e9e189c852b66539372b8d4075)

**Comment by JonathanGiles** [comment]
Great! This can be closed now?

**Comment by anuchandy** [comment]
yes, closing this.
