### ISSUE TITLE
[v3] Upgrade dependency versions

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/autorest-clientruntime-for-java#566]
In v3 Jackson should probably go to 2.9.8 and Netty to 4.1.33.Final

**Comment by JonathanGiles** [comment]
The upgrade to Netty also helps with an issue that @conniey was experiencing in terms of testing code that worked under JDK 8 but failed under JDK 11.

**Comment by anuchandy** [comment]
Upgraded Netty to 4.1.33.Final [PR](https://github.com/Azure/autorest-clientruntime-for-java/pull/568).
Jackson upgrade has to be done bit cautiously since Jackson break the functionality often between versions.

**Comment by anuchandy** [comment]
Jackson update is done as well. Closing
