### ISSUE TITLE
[v3] Restructuring of package names, maven identifiers, etc

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/autorest-clientruntime-for-java#580]
I would like to propose the following restructuring of modules within this repo:

1. **azure-common:** Will receive everything within client-runtime, and all code from azure-client-runtime that is not management-specific.
   1. Package name will become `com.azure.commom`. 
   2. Maven groupId is `com.azure`, artifactId is `azure-common`.

2. **azure-common-mgmt:** Will receive the management-specific code from azure-client-runtime.
   1. Package name will become `com.azure.common.management` (although we should be consistent if the management packages prefer the shorter `mgmt`).
   2. Maven groupId is `com.azure`, artifactId is `azure-common-management` (or `azure-common-mgmt`)

1. **azure-common-auth:** Will receive everything within azure-client-authentication.
   1. Package name will become `com.azure.commom.auth`. 
   2. Maven groupId is `com.azure`, artifactId is `azure-common-auth`.

**Comment by anuchandy** [comment]
@conniey I cannot locate you from available assignee list, so tagging you. let me check why i'cant find you, will get back.

**Comment by anuchandy** [comment]
@JonathanGiles should the package name for `azure-common-mgmt` be `com.azure.common.management` instead of `com.azure.management`?

**Comment by anuchandy** [comment]
Putting this in a table format.

| group id  | artifact id | package name (namespace) |
| ------------- | ------------- |----------------------|
| com.azure  | azure-common  |com.azure.common  |
| com.azure  | azure-common-mgmt  |com.azure.common.mgmt  |
| com.azure  | azure-common-auth  |com.azure.common.auth  |

**Comment by JonathanGiles** [comment]
Yes, sorry, I missed the common name from my original text. Edited it now to fix.

**Comment by anuchandy** [comment]
@JonathanGiles now we that we merged the implementation package work https://github.com/Azure/autorest-clientruntime-for-java/pull/583, I'm going to start package restructuring as discussed in this email.

**Comment by JonathanGiles** [comment]
Great! I will not touch the code today as I need to return to other tasks, but I look forward to reviewing the PR.

**Comment by anuchandy** [comment]
Sounds good, will add you as a reviewer.

**Comment by anuchandy** [comment]
@conniey @JonathanGiles, @jianghaolu, @lmazuel, @mayurid  Here is the PR https://github.com/Azure/autorest-clientruntime-for-java/pull/586, I did highlighted some concerns and additional changes I had to do in PR comment. Please take a look.

**Comment by JonathanGiles** [comment]
For easier review, people may consider browsing Anu's branch here that contains the new structure: https://github.com/anuchandy/autorest-clientruntime-for-java/tree/package-restruct

**Comment by anuchandy** [comment]
thanks @JonathanGiles for the review, PR merged.

**Comment by JonathanGiles** [comment]
Thanks! Mark this issue as resolved! :)

**Comment by anuchandy** [comment]
Closing
