### ISSUE TITLE
[v3] Move internally used types those cannot be make package private to implementation package

### ISSUE THREAD

**Issue by anuchandy** [Azure/autorest-clientruntime-for-java#585]
Few reasons to do this:

1. To communicate that others should be cautious about taking dependency on types in this package.
2. We can exclude those types from JavaDoc.
3. Simplify our life if we move to Java 9+ and it's module system. Types in implementation package won't be able to exported to module.

**Comment by anuchandy** [comment]
PR https://github.com/Azure/autorest-clientruntime-for-java/pull/583 from @JonathanGiles that moves eligible types to implementation package

**Comment by JonathanGiles** [comment]
This can be marked as resolved now

**Comment by anuchandy** [comment]
Closing
