### ISSUE TITLE
Replacing Adal4j with Msal4j

### ISSUE THREAD

**Issue by apescione** [Azure/autorest-clientruntime-for-java#671]
Reading
"This library, ADAL for Java, will no longer receive new feature improvements. Instead, use the new MSAL4J."

and in my project I'm using azure-client-authentication (latest) higher level library tha uses adal4j, my question is when and if this library will migrate to MSAL4J?

Thank you

**Comment by jianghaolu** [comment]
Thanks for suggesting msal4j - we are actually using msal4j for our next gen authentication library here: https://github.com/azure/azure-sdk-for-java/tree/master/sdk/identity/azure-identity. The azure-client-authentication library will be maintained as is and won't receive this update.
