### ISSUE TITLE
Validator Attempts to Reflectively Access Internal JDK APIs

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/autorest-clientruntime-for-java#709]
When using Java 17, and possible other versions of the JDK between 11 and 17, `Validator` causes `InaccessibleObjectException`s to be thrown. These exceptions are being thrown because JDK APIs aren't being opened to `Validator` nor should they being opened to it. The logic being used in `Validator` should be updated to handle module cases that now exist with newer versions of Java.

**Comment by coder-msl** [comment]
Hello, 

maybe my comment posted [here](https://github.com/Azure/azure-sdk-for-java/issues/27806#issuecomment-1784178563)  will be helpful.

**Comment by joshfree** [comment]
@srnagar could you please follow up as our java codegen owner?

related: https://github.com/Azure/azure-sdk-for-java/issues/27806

**Comment by srnagar** [comment]
I will take a look at this issue.

**Comment by srnagar** [comment]
Not fixing the track 1 runtime library in favor of track 2 replacements that will support Java 17
